[build]
  base = "vanzline (14)"
  command = "npm install --include=dev && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/youtube"
  to = "/.netlify/functions/youtube"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
